<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
    <UserSecretsId>1858ec2f-1bd9-418b-8913-d891c324fd1d</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SeedData\Countries.csv" />
    <None Remove="SeedData\GoverningDistricts.csv" />
    <None Remove="SeedData\mobileCarriers.csv" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SeedData\Countries.csv" />
    <EmbeddedResource Include="SeedData\GoverningDistricts.csv" />
    <EmbeddedResource Include="SeedData\mobileCarriers.csv" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Team1.Entities\Team1.Entities.csproj" />
    <ProjectReference Include="..\Team1.Infrastructure.UserIdentity\Team1.Infrastructure.UserIdentity.csproj" />
    <ProjectReference Include="..\Team1.Infrastructure\Team1.Infrastructure.csproj" />
    <ProjectReference Include="..\Team1.Model\Team1.Model.csproj" />
  </ItemGroup>

</Project>
