import { NgModule, Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { CgBusyModule } from 'angular-busy2';

import { CommonService } from './services/common.service';
import { AddressEditComponent } from './addressEdit/addressEdit.component';
import { DirectivesModule, InputYear } from './directives';
import { PipesModule } from './pipes';
import { SmartTablePagerComponent } from './smartTablePager/smartTablePager.component';
import { ImageViewerComponent } from './imageViewer/imageVIewer.component';
import { ModalDefaultFooterButtons } from './modalDefaultFooterButtons/modalDefaultFooterButtons.component';
import { UnsavedChangesNotification } from './unsavedChanges/unsavedChangesNotification.component';
import { InputUnsavedChangesNotification } from './unsavedChanges/inputUnsavedChangesNotification.component';
import { FileUploadModalComponent } from './fileUploadModal/fileUploadModal.component';
import { SpudStringMaxComponent } from './formComponents/text/stringMax.component';
import { SpudPhoneComponent } from './formComponents/text/phone.component';
import { SpudEmailComponent } from './formComponents/text/email.component';
import { SpudCheckboxComponent } from './formComponents/checkboxes/checkbox.component';
import { InputDateComponent } from './formComponents/dates/date.component';
import { BsDatepickerModule } from 'ngx-bootstrap';
import { InputNaturalIntegerComponent } from './formComponents/numbers/naturalInteger.component';
import { TextAreaMaxComponent } from './formComponents/text/testAreaMax.component';
import { DateYearComponent } from './formComponents/dates/dateYear.component';

@Component({
    selector: 'requiredField',
    template: `<span class='requiredField'>*</span>&nbsp;`
})
export class RequiredFieldComponent {
}

@Component({
  selector: 'defaultLabel',
  template: `<requiredField *ngIf="(propertyAttributes.required.value || isRequired) && !suppressRequired"></requiredField>{{propertyAttributes.name}}`
})
export class DefaultLabelComponent {
  /** Should be normal property Attributes object generated by TypeWriter */
  @Input() propertyAttributes: any = {};
  @Input() suppressRequired: boolean = false;
  @Input() isRequired: boolean = false;
}

// must come last
@NgModule({
  imports: [FormsModule, CommonModule, PipesModule, DirectivesModule, CgBusyModule, BsDatepickerModule],
  declarations: [RequiredFieldComponent, DefaultLabelComponent, AddressEditComponent, SmartTablePagerComponent, ImageViewerComponent, ModalDefaultFooterButtons, UnsavedChangesNotification, InputUnsavedChangesNotification, FileUploadModalComponent,
    SpudStringMaxComponent, SpudEmailComponent, SpudPhoneComponent, SpudCheckboxComponent, InputDateComponent, InputNaturalIntegerComponent, TextAreaMaxComponent, DateYearComponent],
  exports: [RequiredFieldComponent, DefaultLabelComponent, AddressEditComponent, SmartTablePagerComponent, ImageViewerComponent, ModalDefaultFooterButtons, UnsavedChangesNotification, InputUnsavedChangesNotification, FileUploadModalComponent,
    SpudStringMaxComponent, SpudEmailComponent, SpudPhoneComponent, SpudCheckboxComponent, InputDateComponent, InputNaturalIntegerComponent, TextAreaMaxComponent, DateYearComponent],
  entryComponents: [FileUploadModalComponent],
  providers: [CommonService]
})
export class ComponentsModule { }
