import { NgModule, Pipe, PipeTransform } from '@angular/core';
import { DatePipe } from '@angular/common';

// inputmask node_modules\inputmask\index.js phone js files (not ".extensions") uncommented so global phone inputmask works.
// when inputmask adds typings can import
//import Inputmask from 'inputmask';
var Inputmask = require('inputmask');

import { globalPhoneMask, usPhoneMask, defaultAngularDateFormat, defaultAngularDateTimeFormat } from 'app.common/constants';

import { IGoverningDistrict } from 'app.common/dtos/GoverningDistrictDto';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { MemberTypeEnum_class } from './enums/MemberTypeEnum';

@Pipe({
    name: "spudYesNo"
})
export class YesNoPipe implements PipeTransform {
    constructor() { }

    transform(value: any, withColor: boolean): string {
        let cssClass = "";
        if (value) {
            cssClass+= "far fa-check-square ";
            if (withColor) cssClass += "text-success";
        }
        else {
            cssClass+= "far fa-square "
            if (withColor) cssClass += "text-warning";
        }
        return `<i class="${cssClass}"></i>`;
    }
}

@Pipe({
  name: "phone"
})
export class PhonePipe implements PipeTransform {
  constructor() { }

  transform(value: any): string {
    if (value == null) return ""
    return Inputmask.format(value, { alias: usPhoneMask });
  }
}

@Pipe({
  name: "globalPhone"
})
export class GlobalPhonePipe implements PipeTransform {
  constructor() { }

  transform(value: any): string {
    if (value == null) return "";
    return Inputmask.format(value, { alias: globalPhoneMask });
  }
}

@Pipe({
  name: "governingDistrictsByCountry"
})
export class GoverningDistrictsByCountryPipe implements PipeTransform {
    constructor() { }

    transform(items: Array<IGoverningDistrict>, countryId: number): Array<IGoverningDistrict> {
        return items.filter((item, index) => { return item.countryId == countryId; });
    }
}

@Pipe({
  name: "defaultDate"
})
export class DefaultDate implements PipeTransform {
  constructor(private datePipe:  DatePipe) { }

  transform(value: any): string | null {
    if (value == null) return "";
    return this.datePipe.transform(value, defaultAngularDateFormat);
  }
}

@Pipe({
  name: "defaultDateTime"
})
export class DefaultDateTime implements PipeTransform {
  constructor(private datePipe: DatePipe) { }

  transform(value: any): string | null {
    if (value == null) return "";
    return this.datePipe.transform(value, defaultAngularDateTimeFormat);
  }
}

@Pipe({
  name: "stringLengthErrorMessage"
})
export class StringLengthErrorMessage implements PipeTransform {
  constructor() { }

  /**
   * Value must be the attribute object generated by typewriter
   */
  transform(value: any): string {
    if (value == null) return "";
    let msg = value.stringLength.errorMessage.replace("{0}", value.name);
    if (value.stringLength.maxLength) {
      msg = msg.replace("{1}", value.stringLength.maxLength.toString());
    }
    if (value.stringLength.minimumLength) {
      msg = msg.replace("{2}", value.stringLength.minimumLength.toString());
    }
    return msg;
  }
}

@Pipe({
  name: "requiredErrorMessage"
})
export class RequiredErrorMessage implements PipeTransform {
  constructor() { }

  /**
   * Value must be the attribute object generated by typewriter
   */
  transform(value: any): string {
    if (value == null) return "";
    let msg = value.required.errorMessage.replace("{0}", value.name);
    
    return msg;
  }
}

@Pipe({
  name: 'truncatetext'
})
export class TruncateTextPipe implements PipeTransform {

  transform(value: string, length: number): string {
    const biggestWord = 50;
    const elipses = "...";

    if (typeof value === "undefined") return value;
    if (value.length <= length) return value;

    //.. truncate to about correct length
    let truncatedText = value.slice(0, length + biggestWord);

    //.. now nibble ends till correct length
    while (truncatedText.length > length - elipses.length) {
      let lastSpace = truncatedText.lastIndexOf(" ");

      if (lastSpace === -1) break;

      truncatedText = truncatedText.slice(0, lastSpace).replace(/[!,.?]$/, '');
    };

    //console.log((truncatedText + elipses).length);

    return truncatedText + elipses;
  }
}

@Pipe({
  name: 'secureImage'
})
export class SecureImagePipe implements PipeTransform {

  constructor(private http: HttpClient) { }

  transform(url: string) {

    return new Observable<string>((observer) => {
      // This is a tiny blank image
      //observer.next('data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==');
      // loading gif
      observer.next('data:image/gif;base64,R0lGODlhKwALAPEAAP///wAAAIKCggAAACH5BAkKAAAAIf4aQ3JlYXRlZCB3aXRoIGFqYXhsb2FkLmluZm8AIf8LTkVUU0NBUEUyLjADAQAAACwAAAAAKwALAAACMoSOCMuW2diD88UKG95W88uF4DaGWFmhZid93pq+pwxnLUnXh8ou+sSz+T64oCAyTBUAACH5BAkKAAAALAAAAAArAAsAAAI9xI4IyyAPYWOxmoTHrHzzmGHe94xkmJifyqFKQ0pwLLgHa82xrekkDrIBZRQab1jyfY7KTtPimixiUsevAAAh+QQJCgAAACwAAAAAKwALAAACPYSOCMswD2FjqZpqW9xv4g8KE7d54XmMpNSgqLoOpgvC60xjNonnyc7p+VKamKw1zDCMR8rp8pksYlKorgAAIfkECQoAAAAsAAAAACsACwAAAkCEjgjLltnYmJS6Bxt+sfq5ZUyoNJ9HHlEqdCfFrqn7DrE2m7Wdj/2y45FkQ13t5itKdshFExC8YCLOEBX6AhQAADs=');
      
      // The next and error callbacks from the observer
      const { next, error } = observer;

      this.http.get(url, { responseType: 'blob', withCredentials:true }).subscribe(response => {
        const reader = new FileReader();
        reader.readAsDataURL(response);
        reader.onloadend = () => {
          observer.next(<any>reader.result);
        };
      });

      return { unsubscribe() { } };
    });
  }
}

@Pipe({
  name: "userMemberTypes"
})
export class UserMemberTypes implements PipeTransform {
  constructor() { }

  /**
   * Value is an array of UserMemberTypeDtos
   */
  transform(value: Array<any>): string {
    if (value == null || value.length == 0) return "";
    let msg: string = "";
    for (var i = 0; i < value.length; i++) {
      if (msg == "")
        msg = MemberTypeEnum_class.enumByNumber[value[i].memberTypeId];
      else
        msg = `${msg}/${MemberTypeEnum_class.enumByNumber[value[i].memberTypeId]}`;
    }

    return msg;
  }
}

// must come last
@NgModule({
  declarations: [YesNoPipe, PhonePipe, GlobalPhonePipe, GoverningDistrictsByCountryPipe, DefaultDate, DefaultDateTime, StringLengthErrorMessage, RequiredErrorMessage, TruncateTextPipe, SecureImagePipe, UserMemberTypes],
  exports: [YesNoPipe, PhonePipe, GlobalPhonePipe, GoverningDistrictsByCountryPipe, DefaultDate, DefaultDateTime, StringLengthErrorMessage, RequiredErrorMessage, TruncateTextPipe, SecureImagePipe, UserMemberTypes],
  providers: [DatePipe],
})
export class PipesModule { }
