<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>2.1.0</Version>
    <Authors>Spud Software, Inc.</Authors>
    <Company>Spud Software, Inc.</Company>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Defines a file manager interface with an injectable local file manager.</Description>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
  </ItemGroup>

</Project>
