 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface ILogin  { 
    
    email?: string;
    password?: string;
    rememberMe?: boolean; 
} 

export class ILogin_PropertyAttributes {
    static readonly email_Attributes = {
      name: "Email", required: { value: true, errorMessage: "{0} is required." }, emailAddress: { errorMessage: "Invalid Email" }, 
      };
       static readonly password_Attributes = {
      name: "Password", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly rememberMe_Attributes = {
      name: "Remember My Email", required: { value: true }, 
      };
      
}

export interface IForgotPassword  { 
    
    email?: string; 
} 

export class IForgotPassword_PropertyAttributes {
    static readonly email_Attributes = {
      name: "Email", required: { value: true, errorMessage: "{0} is required." }, emailAddress: { errorMessage: "Invalid Email" }, 
      };
      
}

export interface ITwoFactorCode  { 
    
    twoFactorCode?: string;
    rememberBrowser?: boolean;
    rememberMe?: boolean;
    email?: string;
    authyUserId?: number;
    userId?: number; 
} 

export class ITwoFactorCode_PropertyAttributes {
    static readonly twoFactorCode_Attributes = {
      name: "Two Factor Code", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly rememberBrowser_Attributes = {
      name: "Remember Browser", required: { value: true }, 
      };
       static readonly rememberMe_Attributes = {
      name: "Remember My Email", required: { value: true }, 
      };
       static readonly email_Attributes = {
      required: { value: false }, name: "Email", 
      };
       static readonly authyUserId_Attributes = {
      required: { value: false }, name: "AuthyUserId", 
      };
       static readonly userId_Attributes = {
      required: { value: false }, name: "UserId", 
      };
      
}

export interface ITwoFactorSetup  { 
    
    phoneNumber?: string;
    countryCode?: string;
    authyUserId?: number;
    userId?: number;
    email?: string; 
} 

export class ITwoFactorSetup_PropertyAttributes {
    static readonly phoneNumber_Attributes = {
      name: "Phone Number", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly countryCode_Attributes = {
      required: { value: false }, name: "CountryCode", 
      };
       static readonly authyUserId_Attributes = {
      required: { value: false }, name: "AuthyUserId", 
      };
       static readonly userId_Attributes = {
      required: { value: true }, name: "UserId", 
      };
       static readonly email_Attributes = {
      required: { value: false }, name: "Email", 
      };
      
}

export interface IResetPassword  { 
    
    email?: string;
    password?: string;
    confirmPassword?: string;
    code?: string; 
} 

export class IResetPassword_PropertyAttributes {
    static readonly email_Attributes = {
      name: "Email", required: { value: true, errorMessage: "{0} is required." }, emailAddress: { errorMessage: "Invalid Email" }, 
      };
       static readonly password_Attributes = {
      name: "Password", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 1000, errorMessage: "Password must be at least {2} characters long.", minimumLength: 12, }, 
      };
       static readonly confirmPassword_Attributes = {
      name: "Confirm Password", required: { value: true, errorMessage: "{0} is required." }, compare: { to: "Password", errorMessage: "Password and confirmation password do not match." }, 
      };
       static readonly code_Attributes = {
      required: { value: false }, name: "Code", 
      };
      
}

export interface IChangePassword  { 
    
    currentPassword?: string;
    password?: string;
    confirmPassword?: string; 
} 

export class IChangePassword_PropertyAttributes {
    static readonly currentPassword_Attributes = {
      name: "Current Password", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly password_Attributes = {
      name: "Password", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 1000, errorMessage: "Password must be at least {2} characters long.", minimumLength: 12, }, 
      };
       static readonly confirmPassword_Attributes = {
      name: "Confirm Password", required: { value: true, errorMessage: "{0} is required." }, compare: { to: "Password", errorMessage: "Password and confirmation password do not match." }, 
      };
      
}
import {IAddress} from './AddressDto';

export interface IRegister  { 
    
    confirmEmail?: string;
    password?: string;
    confirmPassword?: string;
    code?: string;
    addresses?: IAddress[];
    recaptchaToken?: string;
    countryCode?: string;
    authyUserId?: number;
    userId?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phoneNumber?: string;
    birthDate?: Date;
    twoFactorEnabled?: boolean;
    isLoginEnabled?: boolean;
    certificationLevel?: number;
    tripoliNumber?: string;
    narNumber?: string;
    paidThroughYear?: number;
    optOutOfMemberEmails?: boolean;
    optOutOfGeneralEmails?: boolean;
    mobileCarrierId?: number; 
} 

export class IRegister_PropertyAttributes {
    static readonly confirmEmail_Attributes = {
      required: { value: true, errorMessage: "{0} is required." }, name: "Confirm Email", compare: { to: "Email", errorMessage: "Email and email confirmation do not match." }, emailAddress: { errorMessage: "Invalid Email" }, 
      };
       static readonly password_Attributes = {
      name: "Password", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 1000, errorMessage: "Password must be at least {2} characters long.", minimumLength: 12, }, 
      };
       static readonly confirmPassword_Attributes = {
      name: "Confirm Password", required: { value: true, errorMessage: "{0} is required." }, compare: { to: "Password", errorMessage: "Password and confirmation password do not match." }, 
      };
       static readonly code_Attributes = {
      required: { value: false }, name: "Code", 
      };
       static readonly addresses_Attributes = {
      name: "Addresses", required: { value: false }, 
      };
       static readonly recaptchaToken_Attributes = {
      required: { value: false }, name: "RecaptchaToken", 
      };
       static readonly countryCode_Attributes = {
      required: { value: false }, name: "CountryCode", 
      };
       static readonly authyUserId_Attributes = {
      required: { value: false }, name: "AuthyUserId", 
      };
       static readonly userId_Attributes = {
      key: true, required: { value: true }, name: "UserId", 
      };
       static readonly firstName_Attributes = {
      name: "First Name", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly lastName_Attributes = {
      name: "Last Name", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly email_Attributes = {
      required: { value: true, errorMessage: "{0} is required." }, name: "Email", stringLength: { maxLength: 500, errorMessage: "{0} must be < {1} characters.", }, emailAddress: { errorMessage: "Invalid Email" }, 
      };
       static readonly phoneNumber_Attributes = {
      name: "Phone Number", stringLength: { maxLength: 25, }, required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly birthDate_Attributes = {
      name: "Birth Date", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly twoFactorEnabled_Attributes = {
      name: "Two Factor Enable?", required: { value: true }, 
      };
       static readonly isLoginEnabled_Attributes = {
      name: "Enable Login", required: { value: true }, 
      };
       static readonly certificationLevel_Attributes = {
      name: "Cert Level", range: true, required: { value: true }, 
      };
       static readonly tripoliNumber_Attributes = {
      name: "Tripoli #", stringLength: { maxLength: 100, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly narNumber_Attributes = {
      name: "NAR #", stringLength: { maxLength: 100, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly paidThroughYear_Attributes = {
      name: "Paid Through", required: { value: true }, 
      };
       static readonly optOutOfMemberEmails_Attributes = {
      name: "Opt Out of Member Emails", required: { value: true }, 
      };
       static readonly optOutOfGeneralEmails_Attributes = {
      name: "Opt Out of General Emails", required: { value: true }, 
      };
       static readonly mobileCarrierId_Attributes = {
      name: "Mobile Carrier", required: { value: false }, 
      };
      
}

export interface IConfirmEmail  { 
    
    userId?: number;
    code?: string; 
} 

export class IConfirmEmail_PropertyAttributes {
    static readonly userId_Attributes = {
      required: { value: true }, name: "UserId", 
      };
       static readonly code_Attributes = {
      required: { value: false }, name: "Code", 
      };
      
}

export interface IImpersonate  { 
    
    userId?: number; 
} 

export class IImpersonate_PropertyAttributes {
    static readonly userId_Attributes = {
      required: { value: false }, name: "UserId", 
      };
      
}
export var ILogin_PrepareDto = function(dto: ILogin) {		

    
    return dto;
}
export var IForgotPassword_PrepareDto = function(dto: IForgotPassword) {		

    
    return dto;
}
export var ITwoFactorCode_PrepareDto = function(dto: ITwoFactorCode) {		

    
    return dto;
}
export var ITwoFactorSetup_PrepareDto = function(dto: ITwoFactorSetup) {		

    
    return dto;
}
export var IResetPassword_PrepareDto = function(dto: IResetPassword) {		

    
    return dto;
}
export var IChangePassword_PrepareDto = function(dto: IChangePassword) {		

    
    return dto;
}
export var IRegister_PrepareDto = function(dto: IRegister) {		

    if(dto.birthDate != null) {
        dto.birthDate = new Date(<any>dto.birthDate);
    }
    
    return dto;
}
export var IConfirmEmail_PrepareDto = function(dto: IConfirmEmail) {		

    
    return dto;
}
export var IImpersonate_PrepareDto = function(dto: IImpersonate) {		

    
    return dto;
}

