 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {ICountry} from './CountryDto';

export interface IAddressObj  { 
    
    governingDistrictName?: string;
    countryName?: string;
    country?: ICountry;
    address1?: string;
    address2?: string;
    address3?: string;
    city?: string;
    governingDistrictId?: number;
    countryId?: number;
    postalCode?: string; 
} 

export class IAddressObj_PropertyAttributes {
    static readonly governingDistrictName_Attributes = {
      required: { value: false }, name: "GoverningDistrictName", 
      };
       static readonly countryName_Attributes = {
      required: { value: false }, name: "CountryName", 
      };
       static readonly country_Attributes = {
      required: { value: true }, name: "Country", 
      };
       static readonly address1_Attributes = {
      name: "Address Line 1", stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly address2_Attributes = {
      name: "Address Line 2", stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly address3_Attributes = {
      name: "Address Line 3", stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly city_Attributes = {
      name: "City", stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly governingDistrictId_Attributes = {
      name: "Governing District", required: { value: false }, 
      };
       static readonly countryId_Attributes = {
      name: "Country", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly postalCode_Attributes = {
      name: "Postal Code", stringLength: { maxLength: 12, }, required: { value: false }, 
      };
      
}
export var IAddressObj_PrepareDto = function(dto: IAddressObj) {		

    
    return dto;
}

