 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IAddressObj} from './AddressObjDto';

export interface IAddress  { 
    
    addressObj?: IAddressObj;
    isActive?: boolean;
    isUpdated?: boolean;
    isDeleted?: boolean;
    addressId?: number;
    userId?: number; 
} 

export class IAddress_PropertyAttributes {
    static readonly addressObj_Attributes = {
      required: { value: true }, name: "AddressObj", 
      };
       static readonly isActive_Attributes = {
      required: { value: true }, name: "IsActive", 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly isDeleted_Attributes = {
      required: { value: true }, name: "IsDeleted", 
      };
       static readonly addressId_Attributes = {
      key: true, required: { value: true }, name: "AddressId", 
      };
       static readonly userId_Attributes = {
      required: { value: true }, name: "UserId", 
      };
      
}
export var IAddress_PrepareDto = function(dto: IAddress) {		

    
    return dto;
}

