 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IAnnouncement  { 
    
    isActive?: boolean;
    isUpdated?: boolean;
    announcementId?: number;
    title?: string;
    body?: string;
    startShowingOnDate?: Date; 
} 

export class IAnnouncement_PropertyAttributes {
    static readonly isActive_Attributes = {
      name: "Is Active", required: { value: true }, 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly announcementId_Attributes = {
      key: true, required: { value: true }, name: "AnnouncementId", 
      };
       static readonly title_Attributes = {
      name: "Title", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly body_Attributes = {
      name: "Body", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly startShowingOnDate_Attributes = {
      name: "Start Showing On Date", required: { value: true, errorMessage: "{0} is required." }, 
      };
      
}
export var IAnnouncement_PrepareDto = function(dto: IAnnouncement) {		

    if(dto.startShowingOnDate != null) {
        dto.startShowingOnDate = new Date(<any>dto.startShowingOnDate);
    }
    
    return dto;
}

