
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */
import {IAddress} from './AddressDto';

export interface ICompany  { 
    
    addresses?: IAddress[];
    isActive?: boolean;
    isUpdated?: boolean;
    companyId?: number;
    companyName?: string;
    companyCode?: string;
    email?: string;
    phoneNumber?: string;
}

export class ICompany_PropertyAttributes {
    static readonly addresses_Attributes = {
      name: "Addresses", required: { value: false }, 
      };
       static readonly isActive_Attributes = {
      name: "Is Active", required: { value: true }, 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly companyId_Attributes = {
      required: { value: true }, name: "CompanyId", 
      };
       static readonly companyName_Attributes = {
      name: "Company Name", stringLength: { maxLength: 200, errorMessage: "Company name must be < {1} characters", }, required: { value: true, errorMessage: "Company name is required." }, 
      };
       static readonly companyCode_Attributes = {
      name: "Company Code", stringLength: { maxLength: 10, errorMessage: "Company code must be < {1} characters", }, required: { value: true, errorMessage: "Company code is required." }, 
      };
       static readonly email_Attributes = {
      name: "Email", emailAddress: { errorMessage: "Invalid Email" }, stringLength: { maxLength: 500, errorMessage: "Email must be < {1} characters", }, required: { value: true, errorMessage: "Email is required." }, 
      };
       static readonly phoneNumber_Attributes = {
      name: "Phone Number", stringLength: { maxLength: 25, errorMessage: "Phone number must be < {1} characters", }, required: { value: false }, 
      };
      
}
