 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface ICountry  { 
    
    countryId?: number;
    name?: string;
    alpha2?: string;
    alpha3?: string;
    postalCodeMask?: string;
    governingDistrictName?: string; 
} 

export class ICountry_PropertyAttributes {
    static readonly countryId_Attributes = {
      key: true, databaseGenerated: true, required: { value: true }, name: "CountryId", 
      };
       static readonly name_Attributes = {
      stringLength: { maxLength: 100, }, required: { value: true,  }, name: "Name", 
      };
       static readonly alpha2_Attributes = {
      stringLength: { maxLength: 2, }, required: { value: true,  }, name: "Alpha2", 
      };
       static readonly alpha3_Attributes = {
      stringLength: { maxLength: 3, }, required: { value: true,  }, name: "Alpha3", 
      };
       static readonly postalCodeMask_Attributes = {
      stringLength: { maxLength: 10, }, required: { value: false }, name: "PostalCodeMask", 
      };
       static readonly governingDistrictName_Attributes = {
      stringLength: { maxLength: 50, }, required: { value: false }, name: "GoverningDistrictName", 
      };
      
}
export var ICountry_PrepareDto = function(dto: ICountry) {		

    
    return dto;
}

