 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IDocumentObj  { 
    
    documentFilename?: string;
    documentDisplayName?: string;
    mimeType?: string; 
} 

export class IDocumentObj_PropertyAttributes {
    static readonly documentFilename_Attributes = {
      name: "Filename On Disk", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 1000, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly documentDisplayName_Attributes = {
      name: "Filename", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 500, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly mimeType_Attributes = {
      name: "Mime Type", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
      
}
export var IDocumentObj_PrepareDto = function(dto: IDocumentObj) {		

    
    return dto;
}

