 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IEventLocation} from './EventLocationDto';
import {ILocation} from './LocationDto';

export interface IEvent  { 
    
    isActive?: boolean;
    isUpdated?: boolean;
    eventLocations?: IEventLocation[];
    locations?: ILocation[];
    eventId?: number;
    name?: string;
    eventDate?: Date;
    eventAlternateDate?: Date; 
} 

export class IEvent_PropertyAttributes {
    static readonly isActive_Attributes = {
      name: "Is Active", required: { value: true }, 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly eventLocations_Attributes = {
      name: "Locations", required: { value: false }, 
      };
       static readonly locations_Attributes = {
      required: { value: false }, name: "Locations", 
      };
       static readonly eventId_Attributes = {
      key: true, required: { value: true }, name: "EventId", 
      };
       static readonly name_Attributes = {
      name: "Name", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly eventDate_Attributes = {
      name: "Event Date", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly eventAlternateDate_Attributes = {
      name: "Event Alt. Date", required: { value: false }, 
      };
      
}
export var IEvent_PrepareDto = function(dto: IEvent) {		

    if(dto.eventDate != null) {
        dto.eventDate = new Date(<any>dto.eventDate);
    }
    if(dto.eventAlternateDate != null) {
        dto.eventAlternateDate = new Date(<any>dto.eventAlternateDate);
    }
    
    return dto;
}

