 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IEventLocation  { 
    
    isDeleted?: boolean;
    eventId?: number;
    locationId?: number; 
} 

export class IEventLocation_PropertyAttributes {
    static readonly isDeleted_Attributes = {
      required: { value: true }, name: "IsDeleted", 
      };
       static readonly eventId_Attributes = {
      required: { value: true }, name: "EventId", 
      };
       static readonly locationId_Attributes = {
      required: { value: true }, name: "LocationId", 
      };
      
}
export var IEventLocation_PrepareDto = function(dto: IEventLocation) {		

    
    return dto;
}

