 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IGoverningDistrict  { 
    
    governingDistrictId?: number;
    countryId?: number;
    name?: string;
    code?: string; 
} 

export class IGoverningDistrict_PropertyAttributes {
    static readonly governingDistrictId_Attributes = {
      key: true, databaseGenerated: true, required: { value: true }, name: "GoverningDistrictId", 
      };
       static readonly countryId_Attributes = {
      required: { value: true }, name: "CountryId", 
      };
       static readonly name_Attributes = {
      stringLength: { maxLength: 100, }, required: { value: true,  }, name: "Name", 
      };
       static readonly code_Attributes = {
      stringLength: { maxLength: 5, }, required: { value: false }, name: "Code", 
      };
      
}
export var IGoverningDistrict_PrepareDto = function(dto: IGoverningDistrict) {		

    
    return dto;
}

