 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IAddressObj} from './AddressObjDto';

export interface ILocation  { 
    
    isActive?: boolean;
    isUpdated?: boolean;
    addressObj?: IAddressObj;
    locationId?: number;
    locationName?: string;
    locationDescription?: string;
    faaWaiver?: string; 
} 

export class ILocation_PropertyAttributes {
    static readonly isActive_Attributes = {
      name: "Is Active", required: { value: true }, 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly addressObj_Attributes = {
      name: "Address", required: { value: true, errorMessage: "Address is required." }, 
      };
       static readonly locationId_Attributes = {
      key: true, required: { value: true }, name: "LocationId", 
      };
       static readonly locationName_Attributes = {
      name: "Name", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly locationDescription_Attributes = {
      name: "Description", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 2000, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly faaWaiver_Attributes = {
      name: "FAA Waiver", stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
      
}
export var ILocation_PrepareDto = function(dto: ILocation) {		

    
    return dto;
}

