 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IDocumentObj} from './DocumentObjDto';

export interface IPicture  { 
    
    isUpdated?: boolean;
    isActive?: boolean;
    isApproved?: boolean;
    fileKey?: string;
    document?: IDocumentObj;
    fileUpload?: any;
    pictureId?: number;
    ownerUserId?: number;
    approvedByUserId?: number;
    approvedDateTime?: Date;
    description?: string; 
} 

export class IPicture_PropertyAttributes {
    static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly isActive_Attributes = {
      name: "Is Active", required: { value: true }, 
      };
       static readonly isApproved_Attributes = {
      name: "Is Approved", required: { value: true }, 
      };
       static readonly fileKey_Attributes = {
      required: { value: false }, name: "FileKey", 
      };
       static readonly document_Attributes = {
      name: "Picture Upload", required: { value: true }, 
      };
       static readonly fileUpload_Attributes = {
      jsonIgnore: true, required: { value: true }, name: "FileUpload", 
      };
       static readonly pictureId_Attributes = {
      key: true, required: { value: true }, name: "PictureId", 
      };
       static readonly ownerUserId_Attributes = {
      required: { value: true }, name: "OwnerUserId", 
      };
       static readonly approvedByUserId_Attributes = {
      required: { value: false }, name: "ApprovedByUserId", 
      };
       static readonly approvedDateTime_Attributes = {
      required: { value: false }, name: "ApprovedDateTime", 
      };
       static readonly description_Attributes = {
      stringLength: { maxLength: 2000, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, name: "Description", 
      };
      
}
export var IPicture_PrepareDto = function(dto: IPicture) {		

    if(dto.approvedDateTime != null) {
        dto.approvedDateTime = new Date(<any>dto.approvedDateTime);
    }
    
    return dto;
}

