 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IRoleData  { 
    
    grantableRoleIds?: number[]; 
} 

export class IRoleData_PropertyAttributes {
    static readonly grantableRoleIds_Attributes = {
      required: { value: false }, name: "GrantableRoleIds", 
      };
      
}
export var IRoleData_PrepareDto = function(dto: IRoleData) {		

    
    return dto;
}

