 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IRoleData} from './RoleDataDto';

export interface IRole  { 
    
    dataObj?: IRoleData;
    isDeleted?: boolean;
    isAdded?: boolean;
    roleId?: number;
    name?: string;
    normalizedName?: string;
    concurrencyStamp?: string;
    type?: string;
    level?: number;
    data?: string; 
} 

export class IRole_PropertyAttributes {
    static readonly dataObj_Attributes = {
      required: { value: true }, name: "DataObj", 
      };
       static readonly isDeleted_Attributes = {
      required: { value: true }, name: "IsDeleted", 
      };
       static readonly isAdded_Attributes = {
      required: { value: true }, name: "IsAdded", 
      };
       static readonly roleId_Attributes = {
      key: true, databaseGenerated: true, required: { value: true }, name: "RoleId", 
      };
       static readonly name_Attributes = {
      stringLength: { maxLength: 200, }, required: { value: false }, name: "Name", 
      };
       static readonly normalizedName_Attributes = {
      stringLength: { maxLength: 200, }, required: { value: false }, name: "NormalizedName", 
      };
       static readonly concurrencyStamp_Attributes = {
      stringLength: { maxLength: 50, }, required: { value: false }, name: "ConcurrencyStamp", 
      };
       static readonly type_Attributes = {
      stringLength: { maxLength: 50, }, required: { value: false }, name: "Type", 
      };
       static readonly level_Attributes = {
      required: { value: true }, name: "Level", 
      };
       static readonly data_Attributes = {
      required: { value: false }, name: "Data", 
      };
      
}
export var IRole_PrepareDto = function(dto: IRole) {		

    
    return dto;
}

