 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface ISelectOption<T>  { 
    
    value?: T;
    text?: string;
    type?: string;
    description?: string;
    isSelected?: boolean; 
} 

export class ISelectOption_PropertyAttributes {
    static readonly value_Attributes = {
      required: { value: true }, name: "Value", 
      };
       static readonly text_Attributes = {
      required: { value: false }, name: "Text", 
      };
       static readonly type_Attributes = {
      required: { value: false }, name: "Type", 
      };
       static readonly description_Attributes = {
      required: { value: false }, name: "Description", 
      };
       static readonly isSelected_Attributes = {
      required: { value: true }, name: "isSelected", 
      };
      
}

