 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {ITaskMemberType} from './TaskMemberTypeDto';

export interface ITask  { 
    
    dueDate?: string;
    taskCategoryString?: string;
    taskMemberTypesName?: string;
    taskMemberTypes?: ITaskMemberType[];
    isActive?: boolean;
    isUpdated?: boolean;
    taskId?: number;
    taskCategoryId?: number;
    description?: string;
    dueMonth?: number;
    dueDay?: number; 
} 

export class ITask_PropertyAttributes {
    static readonly dueDate_Attributes = {
      name: "Due Date", required: { value: false }, 
      };
       static readonly taskCategoryString_Attributes = {
      required: { value: false }, name: "TaskCategoryString", 
      };
       static readonly taskMemberTypesName_Attributes = {
      required: { value: false }, name: "TaskMemberTypesName", 
      };
       static readonly taskMemberTypes_Attributes = {
      name: "Responsible Member", required: { value: true, errorMessage: "Responsible member is required." }, 
      };
       static readonly isActive_Attributes = {
      name: "Is Active", required: { value: true }, 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly taskId_Attributes = {
      key: true, required: { value: true }, name: "TaskId", 
      };
       static readonly taskCategoryId_Attributes = {
      name: "Category", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly description_Attributes = {
      name: "Description", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 2000, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly dueMonth_Attributes = {
      name: "Due Month", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly dueDay_Attributes = {
      name: "Due Day", required: { value: true, errorMessage: "{0} is required." }, 
      };
      
}
export var ITask_PrepareDto = function(dto: ITask) {		

    
    return dto;
}

