 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface ITaskMemberType  { 
    
    memberTypeString?: string;
    isDeleted?: boolean;
    isAdded?: boolean;
    memberTypeId?: number;
    taskId?: number; 
} 

export class ITaskMemberType_PropertyAttributes {
    static readonly memberTypeString_Attributes = {
      required: { value: false }, name: "MemberTypeString", 
      };
       static readonly isDeleted_Attributes = {
      required: { value: true }, name: "IsDeleted", 
      };
       static readonly isAdded_Attributes = {
      required: { value: true }, name: "IsAdded", 
      };
       static readonly memberTypeId_Attributes = {
      name: "Member Type", required: { value: true }, 
      };
       static readonly taskId_Attributes = {
      required: { value: true }, name: "TaskId", 
      };
      
}
export var ITaskMemberType_PrepareDto = function(dto: ITaskMemberType) {		

    
    return dto;
}

