 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface ITokenUser  { 
    
    email?: string;
    firstName?: string;
    lastName?: string;
    phoneNumber?: string;
    companyName?: string;
    isImpersonatingCompany?: boolean;
    isImpersonatingUser?: boolean; 
} 

export class ITokenUser_PropertyAttributes {
    static readonly email_Attributes = {
      required: { value: false }, name: "Email", 
      };
       static readonly firstName_Attributes = {
      required: { value: false }, name: "FirstName", 
      };
       static readonly lastName_Attributes = {
      required: { value: false }, name: "LastName", 
      };
       static readonly phoneNumber_Attributes = {
      required: { value: false }, name: "PhoneNumber", 
      };
       static readonly companyName_Attributes = {
      required: { value: false }, name: "CompanyName", 
      };
       static readonly isImpersonatingCompany_Attributes = {
      required: { value: true }, name: "IsImpersonatingCompany", 
      };
       static readonly isImpersonatingUser_Attributes = {
      required: { value: true }, name: "IsImpersonatingUser", 
      };
      
}
export var ITokenUser_PrepareDto = function(dto: ITokenUser) {		

    
    return dto;
}

