 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IUserPolicies} from './UserPoliciesDto';
import {ITokenUser} from './TokenUserDto';

export interface IToken  { 
    
    token?: string;
    validTo?: Date;
    refreshToken?: string;
    userPolicies?: IUserPolicies;
    userInfo?: ITokenUser;
    roles?: string[]; 
} 

export class IToken_PropertyAttributes {
    static readonly token_Attributes = {
      required: { value: false }, name: "Token", 
      };
       static readonly validTo_Attributes = {
      required: { value: true }, name: "ValidTo", 
      };
       static readonly refreshToken_Attributes = {
      required: { value: false }, name: "RefreshToken", 
      };
       static readonly userPolicies_Attributes = {
      required: { value: true }, name: "UserPolicies", 
      };
       static readonly userInfo_Attributes = {
      required: { value: true }, name: "UserInfo", 
      };
       static readonly roles_Attributes = {
      name: "Roles", 
      };
      
}

export interface IRefreshToken  { 
    
    refreshToken?: string; 
} 

export class IRefreshToken_PropertyAttributes {
    static readonly refreshToken_Attributes = {
      required: { value: false }, name: "RefreshToken", 
      };
      
}
export var IToken_PrepareDto = function(dto: IToken) {		

    if(dto.validTo != null) {
        dto.validTo = new Date(<any>dto.validTo);
    }
    
    return dto;
}
export var IRefreshToken_PrepareDto = function(dto: IRefreshToken) {		

    
    return dto;
}

