 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IUserPolicies  { 
    
    announcementAddEditDelete?: boolean;
    canImpersonate?: boolean;
    canApprovePicture?: boolean;
    eventAddEditDelete?: boolean;
    locationAddEditDelete?: boolean;
    pictureAddEditDelete?: boolean;
    taskAddEditDelete?: boolean;
    userAddEditDelete?: boolean;
    userProfileEdit?: boolean; 
} 

export class IUserPolicies_PropertyAttributes {
    static readonly announcementAddEditDelete_Attributes = {
      required: { value: true }, name: "AnnouncementAddEditDelete", 
      };
       static readonly canImpersonate_Attributes = {
      required: { value: true }, name: "CanImpersonate", 
      };
       static readonly canApprovePicture_Attributes = {
      required: { value: true }, name: "CanApprovePicture", 
      };
       static readonly eventAddEditDelete_Attributes = {
      required: { value: true }, name: "EventAddEditDelete", 
      };
       static readonly locationAddEditDelete_Attributes = {
      required: { value: true }, name: "LocationAddEditDelete", 
      };
       static readonly pictureAddEditDelete_Attributes = {
      required: { value: true }, name: "PictureAddEditDelete", 
      };
       static readonly taskAddEditDelete_Attributes = {
      required: { value: true }, name: "TaskAddEditDelete", 
      };
       static readonly userAddEditDelete_Attributes = {
      required: { value: true }, name: "UserAddEditDelete", 
      };
       static readonly userProfileEdit_Attributes = {
      required: { value: true }, name: "UserProfileEdit", 
      };
      
}
export var IUserPolicies_PrepareDto = function(dto: IUserPolicies) {		

    
    return dto;
}

