 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */


export interface IUserMemberType  { 
    
    memberTypeString?: string;
    isDeleted?: boolean;
    isAdded?: boolean;
    memberTypeId?: number;
    userId?: number; 
} 

export class IUserMemberType_PropertyAttributes {
    static readonly memberTypeString_Attributes = {
      required: { value: false }, name: "MemberTypeString", 
      };
       static readonly isDeleted_Attributes = {
      required: { value: true }, name: "IsDeleted", 
      };
       static readonly isAdded_Attributes = {
      required: { value: true }, name: "IsAdded", 
      };
       static readonly memberTypeId_Attributes = {
      name: "Member Type", required: { value: true }, 
      };
       static readonly userId_Attributes = {
      required: { value: true }, name: "UserId", 
      };
      
}
export var IUserMemberType_PrepareDto = function(dto: IUserMemberType) {		

    
    return dto;
}

