 
/* Autogenerated by Typewriter do NOT edit
   Dtos.tst is the generating template */

import {IAddress} from './AddressDto';

export interface IUserProfile  { 
    
    addresses?: IAddress[];
    isUpdated?: boolean;
    userId?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phoneNumber?: string;
    birthDate?: Date;
    twoFactorEnabled?: boolean;
    isLoginEnabled?: boolean;
    certificationLevel?: number;
    tripoliNumber?: string;
    narNumber?: string;
    paidThroughYear?: number;
    optOutOfMemberEmails?: boolean;
    optOutOfGeneralEmails?: boolean; 
} 

export class IUserProfile_PropertyAttributes {
    static readonly addresses_Attributes = {
      name: "Addresses", required: { value: false }, 
      };
       static readonly isUpdated_Attributes = {
      required: { value: true }, name: "IsUpdated", 
      };
       static readonly userId_Attributes = {
      key: true, required: { value: true }, name: "UserId", 
      };
       static readonly firstName_Attributes = {
      name: "First Name", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly lastName_Attributes = {
      name: "Last Name", required: { value: true, errorMessage: "{0} is required." }, stringLength: { maxLength: 200, errorMessage: "{0} must be < {1} characters.", }, 
      };
       static readonly email_Attributes = {
      required: { value: true, errorMessage: "{0} is required." }, name: "Email", stringLength: { maxLength: 500, errorMessage: "{0} must be < {1} characters.", }, emailAddress: { errorMessage: "Invalid Email" }, 
      };
       static readonly phoneNumber_Attributes = {
      name: "Phone Number", stringLength: { maxLength: 25, }, required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly birthDate_Attributes = {
      name: "Birth Date", required: { value: true, errorMessage: "{0} is required." }, 
      };
       static readonly twoFactorEnabled_Attributes = {
      name: "Two Factor Enable?", required: { value: true }, 
      };
       static readonly isLoginEnabled_Attributes = {
      name: "Enable Login", required: { value: true }, 
      };
       static readonly certificationLevel_Attributes = {
      name: "Cert Level", range: true, required: { value: true }, 
      };
       static readonly tripoliNumber_Attributes = {
      name: "Tripoli #", stringLength: { maxLength: 100, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly narNumber_Attributes = {
      name: "NAR #", stringLength: { maxLength: 100, errorMessage: "{0} must be < {1} characters.", }, required: { value: false }, 
      };
       static readonly paidThroughYear_Attributes = {
      name: "Paid Through", required: { value: true }, 
      };
       static readonly optOutOfMemberEmails_Attributes = {
      name: "Opt Out of Member Emails", required: { value: true }, 
      };
       static readonly optOutOfGeneralEmails_Attributes = {
      name: "Opt Out of General Emails", required: { value: true }, 
      };
      
}
export var IUserProfile_PrepareDto = function(dto: IUserProfile) {		

    if(dto.birthDate != null) {
        dto.birthDate = new Date(<any>dto.birthDate);
    }
    
    return dto;
}

