<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\Emails\base.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\Emails\base.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services.Filemanager\Services.FileManager.csproj" />
    <ProjectReference Include="..\Team1.Entities\Team1.Entities.csproj" />
    <ProjectReference Include="..\Team1.Infrastructure.Dtos\Team1.Infrastructure.Dtos.csproj" />
    <ProjectReference Include="..\Team1.Model\Team1.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\SharedResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharedValidationResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedValidationResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\SharedResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SharedValidationResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedValidationResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
