// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team1.Entities;

#nullable disable

namespace Team1.Entities.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Team1.Model.APILog", b =>
                {
                    b.Property<long>("APILogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("APILogId"));

                    b.Property<bool>("IncomingRequest")
                        .HasColumnType("bit");

                    b.Property<string>("RequestContentBlock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseContentBlock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TransmissionDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("APILogId");

                    b.ToTable("APILogs");
                });

            modelBuilder.Entity("Team1.Model.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Team1.Model.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartShowingOnDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Team1.Model.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Alpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("GoverningDistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCodeMask")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Team1.Model.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime?>("EventAlternateDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Team1.Model.EventLocation", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("EventLocations");
                });

            modelBuilder.Entity("Team1.Model.GoverningDistrict", b =>
                {
                    b.Property<int>("GoverningDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GoverningDistrictId");

                    b.HasIndex("CountryId");

                    b.ToTable("GoverningDistricts");
                });

            modelBuilder.Entity("Team1.Model.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("FAAWaiver")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Team1.Model.LogType", b =>
                {
                    b.Property<byte>("LogTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LogTypeId");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("Team1.Model.MemberType", b =>
                {
                    b.Property<byte>("MemberTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MemberTypeId");

                    b.ToTable("MemberTypes");
                });

            modelBuilder.Entity("Team1.Model.MobileCarrier", b =>
                {
                    b.Property<int>("MobileCarrierId")
                        .HasColumnType("int");

                    b.Property<string>("MobileCarrierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TextingEmailSuffix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MobileCarrierId");

                    b.ToTable("MobileCarriers");
                });

            modelBuilder.Entity("Team1.Model.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureId"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PictureId");

                    b.HasIndex("UserId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Team1.Model.SystemLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTimeOffset>("EventDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LogGroupKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("LogTypeId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("LogTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("Team1.Model.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("DueDay")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DueMonth")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TaskCategoryId")
                        .HasColumnType("tinyint");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskCategoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Team1.Model.TaskCategory", b =>
                {
                    b.Property<byte>("TaskCategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskCategoryId");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("Team1.Model.TaskMemberType", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<byte>("MemberTypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("TaskId", "MemberTypeId");

                    b.HasIndex("MemberTypeId");

                    b.ToTable("TaskMemberTypes");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.RoleClaim", b =>
                {
                    b.Property<int>("RoleClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.HasKey("RoleClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AuthyUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<byte>("CertificationLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLoginEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastPasswordChangeDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSignInDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MobileCarrierId")
                        .HasColumnType("int");

                    b.Property<string>("NarNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("OptOutOfGeneralEmails")
                        .HasColumnType("bit");

                    b.Property<bool>("OptOutOfMemberEmails")
                        .HasColumnType("bit");

                    b.Property<int>("PaidThroughYear")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TripoliNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("MobileCarrierId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserClaim", b =>
                {
                    b.Property<int>("UserClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserMemberType", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte>("MemberTypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("UserId", "MemberTypeId");

                    b.HasIndex("MemberTypeId");

                    b.ToTable("UserMemberTypes");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRefreshToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresOnDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImpersonationUserId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("ImpersonationUserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Team1.Model.Address", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Team1.Model.OwnedTypes.AddressObj", "AddressObj", b1 =>
                        {
                            b1.Property<int>("AddressId")
                                .HasColumnType("int");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address1");

                            b1.Property<string>("Address2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address2");

                            b1.Property<string>("Address3")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address3");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("City");

                            b1.Property<int?>("CountryId")
                                .IsRequired()
                                .HasColumnType("int")
                                .HasColumnName("CountryId");

                            b1.Property<int?>("GoverningDistrictId")
                                .HasColumnType("int")
                                .HasColumnName("GoverningDistrictId");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("PostalCode");

                            b1.HasKey("AddressId");

                            b1.HasIndex("CountryId");

                            b1.HasIndex("GoverningDistrictId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");

                            b1.HasOne("Team1.Model.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Team1.Model.GoverningDistrict", "GoverningDistrict")
                                .WithMany()
                                .HasForeignKey("GoverningDistrictId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("Country");

                            b1.Navigation("GoverningDistrict");
                        });

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("AddressId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("AddressObj")
                        .IsRequired();

                    b.Navigation("AuditFields")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.Announcement", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("AnnouncementId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("Announcements");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId");
                        });

                    b.Navigation("AuditFields")
                        .IsRequired();
                });

            modelBuilder.Entity("Team1.Model.Event", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("EventId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("AuditFields")
                        .IsRequired();
                });

            modelBuilder.Entity("Team1.Model.EventLocation", b =>
                {
                    b.HasOne("Team1.Model.Event", "Event")
                        .WithMany("EventLocations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team1.Model.Location", "Location")
                        .WithMany("EventLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Team1.Model.GoverningDistrict", b =>
                {
                    b.HasOne("Team1.Model.Country", "Country")
                        .WithMany("GoverningDistricts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Team1.Model.Location", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AddressObj", "AddressObj", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .HasColumnType("int");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address1");

                            b1.Property<string>("Address2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address2");

                            b1.Property<string>("Address3")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address3");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("City");

                            b1.Property<int?>("CountryId")
                                .IsRequired()
                                .HasColumnType("int")
                                .HasColumnName("CountryId");

                            b1.Property<int?>("GoverningDistrictId")
                                .HasColumnType("int")
                                .HasColumnName("GoverningDistrictId");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("PostalCode");

                            b1.HasKey("LocationId");

                            b1.HasIndex("CountryId");

                            b1.HasIndex("GoverningDistrictId");

                            b1.ToTable("Locations");

                            b1.HasOne("Team1.Model.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Team1.Model.GoverningDistrict", "GoverningDistrict")
                                .WithMany()
                                .HasForeignKey("GoverningDistrictId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("LocationId");

                            b1.Navigation("Country");

                            b1.Navigation("GoverningDistrict");
                        });

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("AddressObj")
                        .IsRequired();

                    b.Navigation("AuditFields")
                        .IsRequired();
                });

            modelBuilder.Entity("Team1.Model.Picture", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Pictures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Team1.Model.OwnedTypes.DocumentObj", "DocumentObj", b1 =>
                        {
                            b1.Property<int>("PictureId")
                                .HasColumnType("int");

                            b1.Property<string>("DocumentDisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("DocumentDisplayName");

                            b1.Property<string>("DocumentFilename")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("DocumentFilename");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MimeType");

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("PictureId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.Navigation("AuditFields")
                        .IsRequired();

                    b.Navigation("DocumentObj")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.SystemLog", b =>
                {
                    b.HasOne("Team1.Model.LogType", "LogType")
                        .WithMany("SystemLogs")
                        .HasForeignKey("LogTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LogType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.Task", b =>
                {
                    b.HasOne("Team1.Model.TaskCategory", "TaskCategory")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("TaskId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("TaskId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskId");
                        });

                    b.Navigation("AuditFields")
                        .IsRequired();

                    b.Navigation("TaskCategory");
                });

            modelBuilder.Entity("Team1.Model.TaskMemberType", b =>
                {
                    b.HasOne("Team1.Model.MemberType", "MemberType")
                        .WithMany("TaskMemberTypes")
                        .HasForeignKey("MemberTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team1.Model.Task", "Task")
                        .WithMany("TaskMemberTypes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemberType");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.RoleClaim", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.User", b =>
                {
                    b.HasOne("Team1.Model.MobileCarrier", "MobileCarrier")
                        .WithMany("Users")
                        .HasForeignKey("MobileCarrierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int?>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset?>("CreatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnType("int")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int?>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset?>("UpdatedDateTime")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AuditFields")
                        .IsRequired();

                    b.Navigation("MobileCarrier");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserClaim", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserLogin", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserMemberType", b =>
                {
                    b.HasOne("Team1.Model.MemberType", "MemberType")
                        .WithMany("UserMemberTypes")
                        .HasForeignKey("MemberTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("UserMemberTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemberType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRefreshToken", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "ImpersonationUser")
                        .WithMany()
                        .HasForeignKey("ImpersonationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImpersonationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRole", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserToken", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team1.Model.Country", b =>
                {
                    b.Navigation("GoverningDistricts");
                });

            modelBuilder.Entity("Team1.Model.Event", b =>
                {
                    b.Navigation("EventLocations");
                });

            modelBuilder.Entity("Team1.Model.Location", b =>
                {
                    b.Navigation("EventLocations");
                });

            modelBuilder.Entity("Team1.Model.LogType", b =>
                {
                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("Team1.Model.MemberType", b =>
                {
                    b.Navigation("TaskMemberTypes");

                    b.Navigation("UserMemberTypes");
                });

            modelBuilder.Entity("Team1.Model.MobileCarrier", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Team1.Model.Task", b =>
                {
                    b.Navigation("TaskMemberTypes");
                });

            modelBuilder.Entity("Team1.Model.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Pictures");

                    b.Navigation("Tokens");

                    b.Navigation("UserMemberTypes");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
