// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team1.Entities;

namespace Team1.Entities.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class SpudContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Team1.Model.APILog", b =>
                {
                    b.Property<long>("APILogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IncomingRequest");

                    b.Property<string>("RequestContentBlock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseContentBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseDateTime");

                    b.Property<string>("TargetURL")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("TransmissionDateTime");

                    b.HasKey("APILogId");

                    b.ToTable("APILogs");
                });

            modelBuilder.Entity("Team1.Model.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Team1.Model.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime>("StartShowingOnDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Team1.Model.Country", b =>
                {
                    b.Property<int>("CountryId");

                    b.Property<string>("Alpha2")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("GoverningDistrictName")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PostalCodeMask")
                        .HasMaxLength(10);

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Team1.Model.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EventAlternateDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Team1.Model.EventLocation", b =>
                {
                    b.Property<int>("EventId");

                    b.Property<int>("LocationId");

                    b.HasKey("EventId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("EventLocations");
                });

            modelBuilder.Entity("Team1.Model.GoverningDistrict", b =>
                {
                    b.Property<int>("GoverningDistrictId");

                    b.Property<string>("Code")
                        .HasMaxLength(5);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("GoverningDistrictId");

                    b.HasIndex("CountryId");

                    b.ToTable("GoverningDistricts");
                });

            modelBuilder.Entity("Team1.Model.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FAAWaiver")
                        .HasMaxLength(200);

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Team1.Model.LogType", b =>
                {
                    b.Property<byte>("LogTypeId");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("LogTypeId");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("Team1.Model.MemberType", b =>
                {
                    b.Property<byte>("MemberTypeId");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("MemberTypeId");

                    b.ToTable("MemberTypes");
                });

            modelBuilder.Entity("Team1.Model.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovedByUserId");

                    b.Property<DateTime?>("ApprovedDateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<int>("OwnerUserId");

                    b.Property<int?>("UserId");

                    b.HasKey("PictureId");

                    b.HasIndex("UserId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Team1.Model.SystemLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("EventDateTime");

                    b.Property<string>("EventDescription")
                        .IsRequired();

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50);

                    b.Property<Guid?>("LogGroupKey");

                    b.Property<byte>("LogTypeId");

                    b.Property<int?>("UserId");

                    b.HasKey("LogId");

                    b.HasIndex("LogTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("Team1.Model.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<byte>("DueDay");

                    b.Property<byte>("DueMonth");

                    b.Property<byte>("TaskCategoryId");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskCategoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Team1.Model.TaskCategory", b =>
                {
                    b.Property<byte>("TaskCategoryId");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("TaskCategoryId");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("Team1.Model.TaskMemberType", b =>
                {
                    b.Property<int>("TaskId");

                    b.Property<byte>("MemberTypeId");

                    b.HasKey("TaskId", "MemberTypeId");

                    b.HasIndex("MemberTypeId");

                    b.ToTable("TaskMemberTypes");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.Role", b =>
                {
                    b.Property<byte>("RoleId");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(50);

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.RoleClaim", b =>
                {
                    b.Property<int>("RoleClaimId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<byte>("RoleId");

                    b.HasKey("RoleClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<int?>("AuthyUserId");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<byte>("CertificationLevel");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50);

                    b.Property<bool>("IsLoginEnabled");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTimeOffset?>("LastPasswordChangeDateTime");

                    b.Property<DateTimeOffset?>("LastSignInDateTime");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NarNumber")
                        .HasMaxLength(100);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("OptOutOfGeneralEmails");

                    b.Property<bool>("OptOutOfMemberEmails");

                    b.Property<int>("PaidThroughYear");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("TripoliNumber")
                        .HasMaxLength(100);

                    b.Property<bool>("TwoFactorEnabled");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserClaim", b =>
                {
                    b.Property<int>("UserClaimId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("UserId");

                    b.HasKey("UserClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(2000);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(2000);

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(2000);

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserMemberType", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<byte>("MemberTypeId");

                    b.HasKey("UserId", "MemberTypeId");

                    b.HasIndex("MemberTypeId");

                    b.ToTable("UserMemberTypes");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRefreshToken", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<DateTime>("ExpiresOnDateTime");

                    b.Property<int?>("ImpersonationUserId");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.HasIndex("ImpersonationUserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<byte>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserToken", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .HasMaxLength(1000);

                    b.Property<string>("Value")
                        .HasMaxLength(2000);

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Team1.Model.Address", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Team1.Model.OwnedTypes.AddressObj", "AddressObj", b1 =>
                        {
                            b1.Property<int>("AddressId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnName("Address1")
                                .HasMaxLength(200);

                            b1.Property<string>("Address2")
                                .HasColumnName("Address2")
                                .HasMaxLength(200);

                            b1.Property<string>("Address3")
                                .HasColumnName("Address3")
                                .HasMaxLength(200);

                            b1.Property<string>("City")
                                .HasColumnName("City")
                                .HasMaxLength(200);

                            b1.Property<int>("CountryId")
                                .HasColumnName("CountryId");

                            b1.Property<int?>("GoverningDistrictId")
                                .HasColumnName("GoverningDistrictId");

                            b1.Property<string>("PostalCode")
                                .HasColumnName("PostalCode")
                                .HasMaxLength(12);

                            b1.HasKey("AddressId");

                            b1.HasIndex("CountryId");

                            b1.HasIndex("GoverningDistrictId");

                            b1.ToTable("Addresses");

                            b1.HasOne("Team1.Model.Address")
                                .WithOne("AddressObj")
                                .HasForeignKey("Team1.Model.OwnedTypes.AddressObj", "AddressId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Team1.Model.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Team1.Model.GoverningDistrict", "GoverningDistrict")
                                .WithMany()
                                .HasForeignKey("GoverningDistrictId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("AddressId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.HasOne("Team1.Model.Address")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "AddressId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.Announcement", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("AnnouncementId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("Announcements");

                            b1.HasOne("Team1.Model.Announcement")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "AnnouncementId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.Event", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("EventId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.HasOne("Team1.Model.Event")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "EventId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.EventLocation", b =>
                {
                    b.HasOne("Team1.Model.Event", "Event")
                        .WithMany("EventLocations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.Location", "Location")
                        .WithMany("EventLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.GoverningDistrict", b =>
                {
                    b.HasOne("Team1.Model.Country", "Country")
                        .WithMany("GoverningDistricts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.Location", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AddressObj", "AddressObj", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnName("Address1")
                                .HasMaxLength(200);

                            b1.Property<string>("Address2")
                                .HasColumnName("Address2")
                                .HasMaxLength(200);

                            b1.Property<string>("Address3")
                                .HasColumnName("Address3")
                                .HasMaxLength(200);

                            b1.Property<string>("City")
                                .HasColumnName("City")
                                .HasMaxLength(200);

                            b1.Property<int>("CountryId")
                                .HasColumnName("CountryId");

                            b1.Property<int?>("GoverningDistrictId")
                                .HasColumnName("GoverningDistrictId");

                            b1.Property<string>("PostalCode")
                                .HasColumnName("PostalCode")
                                .HasMaxLength(12);

                            b1.HasKey("LocationId");

                            b1.HasIndex("CountryId");

                            b1.HasIndex("GoverningDistrictId");

                            b1.ToTable("Locations");

                            b1.HasOne("Team1.Model.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Team1.Model.GoverningDistrict", "GoverningDistrict")
                                .WithMany()
                                .HasForeignKey("GoverningDistrictId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Team1.Model.Location")
                                .WithOne("AddressObj")
                                .HasForeignKey("Team1.Model.OwnedTypes.AddressObj", "LocationId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations");

                            b1.HasOne("Team1.Model.Location")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "LocationId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.Picture", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Pictures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Team1.Model.OwnedTypes.DocumentObj", "DocumentObj", b1 =>
                        {
                            b1.Property<int>("PictureId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DocumentDisplayName")
                                .IsRequired()
                                .HasColumnName("DocumentDisplayName")
                                .HasMaxLength(500);

                            b1.Property<string>("DocumentFilename")
                                .IsRequired()
                                .HasColumnName("DocumentFilename")
                                .HasMaxLength(1000);

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasColumnName("MimeType")
                                .HasMaxLength(200);

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.HasOne("Team1.Model.Picture")
                                .WithOne("DocumentObj")
                                .HasForeignKey("Team1.Model.OwnedTypes.DocumentObj", "PictureId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("PictureId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.HasOne("Team1.Model.Picture")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "PictureId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.SystemLog", b =>
                {
                    b.HasOne("Team1.Model.LogType", "LogType")
                        .WithMany("SystemLogs")
                        .HasForeignKey("LogTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.Task", b =>
                {
                    b.HasOne("Team1.Model.TaskCategory", "TaskCategory")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("TaskId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("TaskId");

                            b1.ToTable("Tasks");

                            b1.HasOne("Team1.Model.Task")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "TaskId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.TaskMemberType", b =>
                {
                    b.HasOne("Team1.Model.MemberType", "MemberType")
                        .WithMany("TaskMemberTypes")
                        .HasForeignKey("MemberTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.Task", "Task")
                        .WithMany("TaskMemberTypes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.RoleClaim", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.User", b =>
                {
                    b.OwnsOne("Team1.Model.OwnedTypes.AuditFields", "AuditFields", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CreatedById")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("CreatedDateTime")
                                .HasColumnName("CreatedDateTime");

                            b1.Property<int?>("InactivatedById")
                                .HasColumnName("InactivatedById");

                            b1.Property<DateTimeOffset?>("InactiveDateTime")
                                .HasColumnName("InactiveDateTime");

                            b1.Property<int>("UpdatedById")
                                .HasColumnName("UpdatedById");

                            b1.Property<DateTimeOffset>("UpdatedDateTime")
                                .HasColumnName("UpdatedDateTime");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.HasOne("Team1.Model.UserIdentity.User")
                                .WithOne("AuditFields")
                                .HasForeignKey("Team1.Model.OwnedTypes.AuditFields", "UserId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserClaim", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserLogin", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserMemberType", b =>
                {
                    b.HasOne("Team1.Model.MemberType", "MemberType")
                        .WithMany("UserMemberTypes")
                        .HasForeignKey("MemberTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("UserMemberTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRefreshToken", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "ImpersonationUser")
                        .WithMany()
                        .HasForeignKey("ImpersonationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserRole", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Team1.Model.UserIdentity.UserToken", b =>
                {
                    b.HasOne("Team1.Model.UserIdentity.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
