<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <Version>3.0.2</Version>
    <Description>Spud Emailer
Check out the Readme.md in the repo for how to setup/use.</Description>
    <Company>Spud Software, Inc.</Company>
    <Authors>Spud Software, Inc.</Authors>
    <PackageTags>Spud Emailer Email MailKit</PackageTags>
    <RepositoryUrl>http://process:8080/tfs/SpudSoftware/NuGet/_git/Spud.Services.Email</RepositoryUrl>
    <PackageProjectUrl>http://process:8080/tfs/SpudSoftware/NuGet/_git/73588f66-11db-40ec-880c-2d156a9b3780?_a=contents&amp;path=%2FREADME.md&amp;version=GBmaster</PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.txt" pack="true" PackagePath="." />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
  </ItemGroup>
</Project>