
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class AccountControllerAPI  { 

    /** post: api/Account/Login */
    public static Login = () => {
      
      return `api/Account/Login`;
    };
    
    /** post: api/Account/LoginWith2fa */
    public static LoginWith2fa = () => {
      
      return `api/Account/LoginWith2fa`;
    };
    
    /** post: api/Account/RefreshToken */
    public static RefreshToken = () => {
      
      return `api/Account/RefreshToken`;
    };
    
    /** post: api/Account/Logout */
    public static Logout = () => {
      
      return `api/Account/Logout`;
    };
    
    /** post: api/Account/Register */
    public static Register = () => {
      
      return `api/Account/Register`;
    };
    
    /** get: api/Account/ConfirmUserEmail?userId=${encodeURIComponent(userId)}&code=${encodeURIComponent(code)} */
    public static ConfirmUserEmail = (userId: string, code: string) => {
      
      return `api/Account/ConfirmUserEmail?userId=${encodeURIComponent(userId)}&code=${encodeURIComponent(code)}`;
    };
    
    /** post: api/Account/ForgotPassword */
    public static ForgotPassword = () => {
      
      return `api/Account/ForgotPassword`;
    };
    
    /** post: api/Account/ResetPassword */
    public static ResetPassword = () => {
      
      return `api/Account/ResetPassword`;
    };
    
    /** post: api/Account/ChangePassword */
    public static ChangePassword = () => {
      
      return `api/Account/ChangePassword`;
    };
    
    /** get: api/Account/${id}/SendPasswordResetEmail/${isNew} */
    public static SendPasswordResetEmail = (id: number, isNew: boolean) => {
      
      return `api/Account/${id}/SendPasswordResetEmail/${isNew}`;
    };
    
    /** post: api/Account/TwoFactorSetup */
    public static TwoFactorSetup = () => {
      
      return `api/Account/TwoFactorSetup`;
    };
    
    /** post: api/Account/Impersonate */
    public static Impersonate = () => {
      
      return `api/Account/Impersonate`;
    };
    
}
