
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class AddressesControllerAPI  { 

    /** get: api/Addresses/User/${userId} */
    public static GetUserAddresses = (userId: number) => {
      
      return `api/Addresses/User/${userId}`;
    };
    
}
