
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class AnnouncementsControllerAPI  { 

    /** get: api/Announcements */
    public static GetAnnouncements = () => {
      
      return `api/Announcements`;
    };
    
    /** get: api/Announcements/ForDashboard */
    public static GetAnnouncementsForDashboard = () => {
      
      return `api/Announcements/ForDashboard`;
    };
    
    /** post: api/Announcements */
    public static CreateAnnouncement = () => {
      
      return `api/Announcements`;
    };
    
    /** put: api/Announcements */
    public static UpdateAnnouncement = () => {
      
      return `api/Announcements`;
    };
    
    /** delete: api/Announcements/${id} */
    public static DeleteAnnouncement = (id: number) => {
      
      return `api/Announcements/${id}`;
    };
    
}
