${
    // Enable extension methods by adding using Typewriter.Extensions.*
    using Typewriter.Extensions.Types;
    using Typewriter.Extensions.WebApi;
    string ClassName(Class c) 
    {
        return MakeClassName(c.Name);
    }
    string MakeClassName(string name)
    {
        return name + "API";
    }

    string GetParameterType(Parameter parameter)
    {
        var name = parameter.Type.Name;
        if (parameter.Type.IsNullable)
            name += " | undefined";
            
        return name; 
    }

    string UpdateParameterValueForUri(Parameter p)
    { 
      if(p.Type.IsDate && !p.Type.IsNullable)
          return $"{p.name} = <any>{p.name}.toISOString();";
      return null;
    }
}
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */
$Classes(c=>c.Name.EndsWith("Controller") && !c.Attributes.Any(cc=>cc.Name == "TypeWriterIgnore"))[
export class $ClassName  { 
$Methods[
    /** $HttpMethod: $Url */
    public static $Name = ($Parameters(p => p.Type.IsPrimitive)[$name: $GetParameterType][, ]) => {
      $Parameters(p => p.Type.IsPrimitive)[$UpdateParameterValueForUri]
      return `$Url`;
    };
    ]
}]
