
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class CompaniesControllerAPI  { 

    /** get: api/Companies */
    public static GetCompanies = () => {
      
      return `api/Companies`;
    };
    
    /** post: api/Companies */
    public static CreateCompany = () => {
      
      return `api/Companies`;
    };
    
    /** put: api/Companies */
    public static UpdateCompany = () => {
      
      return `api/Companies`;
    };
    
    /** delete: api/Companies/${id} */
    public static DeleteCompany = (id: number) => {
      
      return `api/Companies/${id}`;
    };
    
}
