
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class CountriesControllerAPI  { 

    /** get: api/Countries */
    public static GetCountries = () => {
      
      return `api/Countries`;
    };
    
}
