
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class EventsControllerAPI  { 

    /** get: api/Events */
    public static GetEvents = () => {
      
      return `api/Events`;
    };
    
    /** get: api/Events/ForDashboard */
    public static GetEventsForDashboard = () => {
      
      return `api/Events/ForDashboard`;
    };
    
    /** post: api/Events */
    public static CreateEvent = () => {
      
      return `api/Events`;
    };
    
    /** put: api/Events */
    public static UpdateEvent = () => {
      
      return `api/Events`;
    };
    
    /** delete: api/Events/${id} */
    public static DeleteEvent = (id: number) => {
      
      return `api/Events/${id}`;
    };
    
}
