
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class GoverningDistrictsControllerAPI  { 

    /** get: api/GoverningDistricts */
    public static GetGoverningDistricts = () => {
      
      return `api/GoverningDistricts`;
    };
    
}
