
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class LocationsControllerAPI  { 

    /** get: api/Locations */
    public static GetLocations = () => {
      
      return `api/Locations`;
    };
    
    /** get: api/Locations/ForSelection */
    public static GetLocationsForSelection = () => {
      
      return `api/Locations/ForSelection`;
    };
    
    /** post: api/Locations */
    public static CreateLocation = () => {
      
      return `api/Locations`;
    };
    
    /** put: api/Locations */
    public static UpdateLocation = () => {
      
      return `api/Locations`;
    };
    
    /** delete: api/Locations/${id} */
    public static DeleteLocation = (id: number) => {
      
      return `api/Locations/${id}`;
    };
    
}
