
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class ManageControllerAPI  { 

    /** get: api/Manage */
    public static GetUserProfile = () => {
      
      return `api/Manage`;
    };
    
    /** put: api/Manage */
    public static UpdateUserProfile = () => {
      
      return `api/Manage`;
    };
    
}
