
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class MobileCarriersControllerAPI  { 

    /** get: api/MobileCarriers */
    public static GetMobileCarriers = () => {
      
      return `api/MobileCarriers`;
    };
    
}
