
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class PicturesControllerAPI  { 

    /** get: api/Pictures/${galleryType} */
    public static GetPictures = (galleryType: number) => {
      
      return `api/Pictures/${galleryType}`;
    };
    
    /** get: api/Pictures */
    public static GetRandomPictures = () => {
      
      return `api/Pictures`;
    };
    
    /** get: api/Pictures/${id}/viewing */
    public static GetPictureForViewing = (id: number) => {
      
      return `api/Pictures/${id}/viewing`;
    };
    
    /** get: api/Pictures/GalleryTypes */
    public static GetGalleryTypes = () => {
      
      return `api/Pictures/GalleryTypes`;
    };
    
    /** post: api/Pictures */
    public static CreatePicture = () => {
      
      return `api/Pictures`;
    };
    
    /** put: api/Pictures */
    public static UpdatePicture = () => {
      
      return `api/Pictures`;
    };
    
    /** delete: api/Pictures/${id} */
    public static DeletePicture = (id: number) => {
      
      return `api/Pictures/${id}`;
    };
    
}
