
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class RolesControllerAPI  { 

    /** get: api/Roles */
    public static GetGrantableRoles = () => {
      
      return `api/Roles`;
    };
    
}
