
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class TasksControllerAPI  { 

    /** get: api/Tasks */
    public static GetTasks = () => {
      
      return `api/Tasks`;
    };
    
    /** post: api/Tasks */
    public static CreateTask = () => {
      
      return `api/Tasks`;
    };
    
    /** put: api/Tasks */
    public static UpdateTask = () => {
      
      return `api/Tasks`;
    };
    
    /** delete: api/Tasks/${id} */
    public static DeleteTask = (id: number) => {
      
      return `api/Tasks/${id}`;
    };
    
}
