
/* Autogenerated by Typewriter do NOT edit
   APIs.tst is the generating template */

export class UsersControllerAPI  { 

    /** get: api/Users */
    public static GetUsers = () => {
      
      return `api/Users`;
    };
    
    /** get: api/Users/BoD */
    public static GetBoardOfDirectors = () => {
      
      return `api/Users/BoD`;
    };
    
    /** post: api/Users */
    public static CreateUser = () => {
      
      return `api/Users`;
    };
    
    /** put: api/Users */
    public static UpdateUser = () => {
      
      return `api/Users`;
    };
    
    /** delete: api/Users/${id} */
    public static DeleteUser = (id: number) => {
      
      return `api/Users/${id}`;
    };
    
}
